// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kerberos

import (
	"context"

	"github.com/mk6i/open-oscar-server/config"
	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockAuthService creates a new instance of mockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthService {
	mock := &mockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAuthService is an autogenerated mock type for the AuthService type
type mockAuthService struct {
	mock.Mock
}

type mockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuthService) EXPECT() *mockAuthService_Expecter {
	return &mockAuthService_Expecter{mock: &_m.Mock}
}

// KerberosLogin provides a mock function for the type mockAuthService
func (_mock *mockAuthService) KerberosLogin(ctx context.Context, inBody wire.SNAC_0x050C_0x0002_KerberosLoginRequest, endpointCfg config.Endpoint) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, inBody, endpointCfg)

	if len(ret) == 0 {
		panic("no return value specified for KerberosLogin")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNAC_0x050C_0x0002_KerberosLoginRequest, config.Endpoint) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, inBody, endpointCfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNAC_0x050C_0x0002_KerberosLoginRequest, config.Endpoint) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inBody, endpointCfg)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.SNAC_0x050C_0x0002_KerberosLoginRequest, config.Endpoint) error); ok {
		r1 = returnFunc(ctx, inBody, endpointCfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_KerberosLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KerberosLogin'
type mockAuthService_KerberosLogin_Call struct {
	*mock.Call
}

// KerberosLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - inBody wire.SNAC_0x050C_0x0002_KerberosLoginRequest
//   - endpointCfg config.Endpoint
func (_e *mockAuthService_Expecter) KerberosLogin(ctx interface{}, inBody interface{}, endpointCfg interface{}) *mockAuthService_KerberosLogin_Call {
	return &mockAuthService_KerberosLogin_Call{Call: _e.mock.On("KerberosLogin", ctx, inBody, endpointCfg)}
}

func (_c *mockAuthService_KerberosLogin_Call) Run(run func(ctx context.Context, inBody wire.SNAC_0x050C_0x0002_KerberosLoginRequest, endpointCfg config.Endpoint)) *mockAuthService_KerberosLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNAC_0x050C_0x0002_KerberosLoginRequest
		if args[1] != nil {
			arg1 = args[1].(wire.SNAC_0x050C_0x0002_KerberosLoginRequest)
		}
		var arg2 config.Endpoint
		if args[2] != nil {
			arg2 = args[2].(config.Endpoint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthService_KerberosLogin_Call) Return(sNACMessage wire.SNACMessage, err error) *mockAuthService_KerberosLogin_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockAuthService_KerberosLogin_Call) RunAndReturn(run func(ctx context.Context, inBody wire.SNAC_0x050C_0x0002_KerberosLoginRequest, endpointCfg config.Endpoint) (wire.SNACMessage, error)) *mockAuthService_KerberosLogin_Call {
	_c.Call.Return(run)
	return _c
}
