// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package webapi

import (
	"context"

	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockDirSearchService creates a new instance of mockDirSearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDirSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDirSearchService {
	mock := &mockDirSearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDirSearchService is an autogenerated mock type for the DirSearchService type
type mockDirSearchService struct {
	mock.Mock
}

type mockDirSearchService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDirSearchService) EXPECT() *mockDirSearchService_Expecter {
	return &mockDirSearchService_Expecter{mock: &_m.Mock}
}

// InfoQuery provides a mock function for the type mockDirSearchService
func (_mock *mockDirSearchService) InfoQuery(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0F_0x02_InfoQuery) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for InfoQuery")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0F_0x02_InfoQuery) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, inFrame, inBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0F_0x02_InfoQuery) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inFrame, inBody)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.SNACFrame, wire.SNAC_0x0F_0x02_InfoQuery) error); ok {
		r1 = returnFunc(ctx, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDirSearchService_InfoQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoQuery'
type mockDirSearchService_InfoQuery_Call struct {
	*mock.Call
}

// InfoQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x0F_0x02_InfoQuery
func (_e *mockDirSearchService_Expecter) InfoQuery(ctx interface{}, inFrame interface{}, inBody interface{}) *mockDirSearchService_InfoQuery_Call {
	return &mockDirSearchService_InfoQuery_Call{Call: _e.mock.On("InfoQuery", ctx, inFrame, inBody)}
}

func (_c *mockDirSearchService_InfoQuery_Call) Run(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0F_0x02_InfoQuery)) *mockDirSearchService_InfoQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNACFrame
		if args[1] != nil {
			arg1 = args[1].(wire.SNACFrame)
		}
		var arg2 wire.SNAC_0x0F_0x02_InfoQuery
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x0F_0x02_InfoQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockDirSearchService_InfoQuery_Call) Return(sNACMessage wire.SNACMessage, err error) *mockDirSearchService_InfoQuery_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockDirSearchService_InfoQuery_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.SNACFrame, inBody wire.SNAC_0x0F_0x02_InfoQuery) (wire.SNACMessage, error)) *mockDirSearchService_InfoQuery_Call {
	_c.Call.Return(run)
	return _c
}
