// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package webapi

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockBuddyBroadcaster creates a new instance of mockBuddyBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBuddyBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBuddyBroadcaster {
	mock := &mockBuddyBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBuddyBroadcaster is an autogenerated mock type for the BuddyBroadcaster type
type mockBuddyBroadcaster struct {
	mock.Mock
}

type mockBuddyBroadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBuddyBroadcaster) EXPECT() *mockBuddyBroadcaster_Expecter {
	return &mockBuddyBroadcaster_Expecter{mock: &_m.Mock}
}

// BroadcastBuddyArrived provides a mock function for the type mockBuddyBroadcaster
func (_mock *mockBuddyBroadcaster) BroadcastBuddyArrived(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo) error {
	ret := _mock.Called(ctx, screenName, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastBuddyArrived")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName, wire.TLVUserInfo) error); ok {
		r0 = returnFunc(ctx, screenName, userInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyBroadcaster_BroadcastBuddyArrived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastBuddyArrived'
type mockBuddyBroadcaster_BroadcastBuddyArrived_Call struct {
	*mock.Call
}

// BroadcastBuddyArrived is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
//   - userInfo wire.TLVUserInfo
func (_e *mockBuddyBroadcaster_Expecter) BroadcastBuddyArrived(ctx interface{}, screenName interface{}, userInfo interface{}) *mockBuddyBroadcaster_BroadcastBuddyArrived_Call {
	return &mockBuddyBroadcaster_BroadcastBuddyArrived_Call{Call: _e.mock.On("BroadcastBuddyArrived", ctx, screenName, userInfo)}
}

func (_c *mockBuddyBroadcaster_BroadcastBuddyArrived_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo)) *mockBuddyBroadcaster_BroadcastBuddyArrived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		var arg2 wire.TLVUserInfo
		if args[2] != nil {
			arg2 = args[2].(wire.TLVUserInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyBroadcaster_BroadcastBuddyArrived_Call) Return(err error) *mockBuddyBroadcaster_BroadcastBuddyArrived_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyBroadcaster_BroadcastBuddyArrived_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName, userInfo wire.TLVUserInfo) error) *mockBuddyBroadcaster_BroadcastBuddyArrived_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastBuddyDeparted provides a mock function for the type mockBuddyBroadcaster
func (_mock *mockBuddyBroadcaster) BroadcastBuddyDeparted(ctx context.Context, screenName state.IdentScreenName) error {
	ret := _mock.Called(ctx, screenName)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastBuddyDeparted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.IdentScreenName) error); ok {
		r0 = returnFunc(ctx, screenName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyBroadcaster_BroadcastBuddyDeparted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastBuddyDeparted'
type mockBuddyBroadcaster_BroadcastBuddyDeparted_Call struct {
	*mock.Call
}

// BroadcastBuddyDeparted is a helper method to define mock.On call
//   - ctx context.Context
//   - screenName state.IdentScreenName
func (_e *mockBuddyBroadcaster_Expecter) BroadcastBuddyDeparted(ctx interface{}, screenName interface{}) *mockBuddyBroadcaster_BroadcastBuddyDeparted_Call {
	return &mockBuddyBroadcaster_BroadcastBuddyDeparted_Call{Call: _e.mock.On("BroadcastBuddyDeparted", ctx, screenName)}
}

func (_c *mockBuddyBroadcaster_BroadcastBuddyDeparted_Call) Run(run func(ctx context.Context, screenName state.IdentScreenName)) *mockBuddyBroadcaster_BroadcastBuddyDeparted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.IdentScreenName
		if args[1] != nil {
			arg1 = args[1].(state.IdentScreenName)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockBuddyBroadcaster_BroadcastBuddyDeparted_Call) Return(err error) *mockBuddyBroadcaster_BroadcastBuddyDeparted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyBroadcaster_BroadcastBuddyDeparted_Call) RunAndReturn(run func(ctx context.Context, screenName state.IdentScreenName) error) *mockBuddyBroadcaster_BroadcastBuddyDeparted_Call {
	_c.Call.Return(run)
	return _c
}
