// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package webapi

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockBuddyService creates a new instance of mockBuddyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBuddyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBuddyService {
	mock := &mockBuddyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockBuddyService is an autogenerated mock type for the BuddyService type
type mockBuddyService struct {
	mock.Mock
}

type mockBuddyService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBuddyService) EXPECT() *mockBuddyService_Expecter {
	return &mockBuddyService_Expecter{mock: &_m.Mock}
}

// AddTempBuddies provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) AddTempBuddies(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) (*wire.SNACMessage, error) {
	ret := _mock.Called(ctx, instance, inFrame, inBody)

	if len(ret) == 0 {
		panic("no return value specified for AddTempBuddies")
	}

	var r0 *wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) (*wire.SNACMessage, error)); ok {
		return returnFunc(ctx, instance, inFrame, inBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) *wire.SNACMessage); ok {
		r0 = returnFunc(ctx, instance, inFrame, inBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wire.SNACMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) error); ok {
		r1 = returnFunc(ctx, instance, inFrame, inBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockBuddyService_AddTempBuddies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTempBuddies'
type mockBuddyService_AddTempBuddies_Call struct {
	*mock.Call
}

// AddTempBuddies is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies
func (_e *mockBuddyService_Expecter) AddTempBuddies(ctx interface{}, instance interface{}, inFrame interface{}, inBody interface{}) *mockBuddyService_AddTempBuddies_Call {
	return &mockBuddyService_AddTempBuddies_Call{Call: _e.mock.On("AddTempBuddies", ctx, instance, inFrame, inBody)}
}

func (_c *mockBuddyService_AddTempBuddies_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies)) *mockBuddyService_AddTempBuddies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNACFrame
		if args[2] != nil {
			arg2 = args[2].(wire.SNACFrame)
		}
		var arg3 wire.SNAC_0x03_0x0F_BuddyAddTempBuddies
		if args[3] != nil {
			arg3 = args[3].(wire.SNAC_0x03_0x0F_BuddyAddTempBuddies)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockBuddyService_AddTempBuddies_Call) Return(sNACMessage *wire.SNACMessage, err error) *mockBuddyService_AddTempBuddies_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockBuddyService_AddTempBuddies_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x03_0x0F_BuddyAddTempBuddies) (*wire.SNACMessage, error)) *mockBuddyService_AddTempBuddies_Call {
	_c.Call.Return(run)
	return _c
}

// DelTempBuddies provides a mock function for the type mockBuddyService
func (_mock *mockBuddyService) DelTempBuddies(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for DelTempBuddies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x03_0x10_BuddyDelTempBuddies) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockBuddyService_DelTempBuddies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelTempBuddies'
type mockBuddyService_DelTempBuddies_Call struct {
	*mock.Call
}

// DelTempBuddies is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies
func (_e *mockBuddyService_Expecter) DelTempBuddies(ctx interface{}, instance interface{}, inBody interface{}) *mockBuddyService_DelTempBuddies_Call {
	return &mockBuddyService_DelTempBuddies_Call{Call: _e.mock.On("DelTempBuddies", ctx, instance, inBody)}
}

func (_c *mockBuddyService_DelTempBuddies_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies)) *mockBuddyService_DelTempBuddies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x03_0x10_BuddyDelTempBuddies
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x03_0x10_BuddyDelTempBuddies)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockBuddyService_DelTempBuddies_Call) Return(err error) *mockBuddyService_DelTempBuddies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockBuddyService_DelTempBuddies_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x03_0x10_BuddyDelTempBuddies) error) *mockBuddyService_DelTempBuddies_Call {
	_c.Call.Return(run)
	return _c
}
