// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oscar

import (
	"context"

	"github.com/mk6i/open-oscar-server/state"
	mock "github.com/stretchr/testify/mock"
)

// newMockRateLimitUpdater creates a new instance of mockRateLimitUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRateLimitUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRateLimitUpdater {
	mock := &mockRateLimitUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRateLimitUpdater is an autogenerated mock type for the RateLimitUpdater type
type mockRateLimitUpdater struct {
	mock.Mock
}

type mockRateLimitUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRateLimitUpdater) EXPECT() *mockRateLimitUpdater_Expecter {
	return &mockRateLimitUpdater_Expecter{mock: &_m.Mock}
}

// MonitorRateLimits provides a mock function for the type mockRateLimitUpdater
func (_mock *mockRateLimitUpdater) MonitorRateLimits(ctx context.Context, session *state.Session) {
	_mock.Called(ctx, session)
	return
}

// mockRateLimitUpdater_MonitorRateLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonitorRateLimits'
type mockRateLimitUpdater_MonitorRateLimits_Call struct {
	*mock.Call
}

// MonitorRateLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - session *state.Session
func (_e *mockRateLimitUpdater_Expecter) MonitorRateLimits(ctx interface{}, session interface{}) *mockRateLimitUpdater_MonitorRateLimits_Call {
	return &mockRateLimitUpdater_MonitorRateLimits_Call{Call: _e.mock.On("MonitorRateLimits", ctx, session)}
}

func (_c *mockRateLimitUpdater_MonitorRateLimits_Call) Run(run func(ctx context.Context, session *state.Session)) *mockRateLimitUpdater_MonitorRateLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRateLimitUpdater_MonitorRateLimits_Call) Return() *mockRateLimitUpdater_MonitorRateLimits_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockRateLimitUpdater_MonitorRateLimits_Call) RunAndReturn(run func(ctx context.Context, session *state.Session)) *mockRateLimitUpdater_MonitorRateLimits_Call {
	_c.Run(run)
	return _c
}
