// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package foodgroup

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockCookieBaker creates a new instance of mockCookieBaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCookieBaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCookieBaker {
	mock := &mockCookieBaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockCookieBaker is an autogenerated mock type for the CookieBaker type
type mockCookieBaker struct {
	mock.Mock
}

type mockCookieBaker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCookieBaker) EXPECT() *mockCookieBaker_Expecter {
	return &mockCookieBaker_Expecter{mock: &_m.Mock}
}

// Crack provides a mock function for the type mockCookieBaker
func (_mock *mockCookieBaker) Crack(data []byte) ([]byte, time.Time, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Crack")
	}

	var r0 []byte
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, time.Time, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) time.Time); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = returnFunc(data)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockCookieBaker_Crack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Crack'
type mockCookieBaker_Crack_Call struct {
	*mock.Call
}

// Crack is a helper method to define mock.On call
//   - data []byte
func (_e *mockCookieBaker_Expecter) Crack(data interface{}) *mockCookieBaker_Crack_Call {
	return &mockCookieBaker_Crack_Call{Call: _e.mock.On("Crack", data)}
}

func (_c *mockCookieBaker_Crack_Call) Run(run func(data []byte)) *mockCookieBaker_Crack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockCookieBaker_Crack_Call) Return(bytes []byte, time1 time.Time, err error) *mockCookieBaker_Crack_Call {
	_c.Call.Return(bytes, time1, err)
	return _c
}

func (_c *mockCookieBaker_Crack_Call) RunAndReturn(run func(data []byte) ([]byte, time.Time, error)) *mockCookieBaker_Crack_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type mockCookieBaker
func (_mock *mockCookieBaker) Issue(data []byte, ttl time.Duration) ([]byte, error) {
	ret := _mock.Called(data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, time.Duration) ([]byte, error)); ok {
		return returnFunc(data, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, time.Duration) []byte); ok {
		r0 = returnFunc(data, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, time.Duration) error); ok {
		r1 = returnFunc(data, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockCookieBaker_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type mockCookieBaker_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - data []byte
//   - ttl time.Duration
func (_e *mockCookieBaker_Expecter) Issue(data interface{}, ttl interface{}) *mockCookieBaker_Issue_Call {
	return &mockCookieBaker_Issue_Call{Call: _e.mock.On("Issue", data, ttl)}
}

func (_c *mockCookieBaker_Issue_Call) Run(run func(data []byte, ttl time.Duration)) *mockCookieBaker_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockCookieBaker_Issue_Call) Return(bytes []byte, err error) *mockCookieBaker_Issue_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *mockCookieBaker_Issue_Call) RunAndReturn(run func(data []byte, ttl time.Duration) ([]byte, error)) *mockCookieBaker_Issue_Call {
	_c.Call.Return(run)
	return _c
}
