// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toc

import (
	"context"

	"github.com/google/uuid"
	"github.com/mk6i/open-oscar-server/config"
	"github.com/mk6i/open-oscar-server/state"
	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockAuthService creates a new instance of mockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthService {
	mock := &mockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAuthService is an autogenerated mock type for the AuthService type
type mockAuthService struct {
	mock.Mock
}

type mockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuthService) EXPECT() *mockAuthService_Expecter {
	return &mockAuthService_Expecter{mock: &_m.Mock}
}

// BUCPChallenge provides a mock function for the type mockAuthService
func (_mock *mockAuthService) BUCPChallenge(ctx context.Context, inBody wire.SNAC_0x17_0x06_BUCPChallengeRequest, newUUID func() uuid.UUID) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, inBody, newUUID)

	if len(ret) == 0 {
		panic("no return value specified for BUCPChallenge")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNAC_0x17_0x06_BUCPChallengeRequest, func() uuid.UUID) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, inBody, newUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNAC_0x17_0x06_BUCPChallengeRequest, func() uuid.UUID) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inBody, newUUID)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.SNAC_0x17_0x06_BUCPChallengeRequest, func() uuid.UUID) error); ok {
		r1 = returnFunc(ctx, inBody, newUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_BUCPChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BUCPChallenge'
type mockAuthService_BUCPChallenge_Call struct {
	*mock.Call
}

// BUCPChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - inBody wire.SNAC_0x17_0x06_BUCPChallengeRequest
//   - newUUID func() uuid.UUID
func (_e *mockAuthService_Expecter) BUCPChallenge(ctx interface{}, inBody interface{}, newUUID interface{}) *mockAuthService_BUCPChallenge_Call {
	return &mockAuthService_BUCPChallenge_Call{Call: _e.mock.On("BUCPChallenge", ctx, inBody, newUUID)}
}

func (_c *mockAuthService_BUCPChallenge_Call) Run(run func(ctx context.Context, inBody wire.SNAC_0x17_0x06_BUCPChallengeRequest, newUUID func() uuid.UUID)) *mockAuthService_BUCPChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNAC_0x17_0x06_BUCPChallengeRequest
		if args[1] != nil {
			arg1 = args[1].(wire.SNAC_0x17_0x06_BUCPChallengeRequest)
		}
		var arg2 func() uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(func() uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthService_BUCPChallenge_Call) Return(sNACMessage wire.SNACMessage, err error) *mockAuthService_BUCPChallenge_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockAuthService_BUCPChallenge_Call) RunAndReturn(run func(ctx context.Context, inBody wire.SNAC_0x17_0x06_BUCPChallengeRequest, newUUID func() uuid.UUID) (wire.SNACMessage, error)) *mockAuthService_BUCPChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// BUCPLogin provides a mock function for the type mockAuthService
func (_mock *mockAuthService) BUCPLogin(ctx context.Context, inBody wire.SNAC_0x17_0x02_BUCPLoginRequest, endpointCfg config.Endpoint) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, inBody, endpointCfg)

	if len(ret) == 0 {
		panic("no return value specified for BUCPLogin")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNAC_0x17_0x02_BUCPLoginRequest, config.Endpoint) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, inBody, endpointCfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.SNAC_0x17_0x02_BUCPLoginRequest, config.Endpoint) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, inBody, endpointCfg)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.SNAC_0x17_0x02_BUCPLoginRequest, config.Endpoint) error); ok {
		r1 = returnFunc(ctx, inBody, endpointCfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_BUCPLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BUCPLogin'
type mockAuthService_BUCPLogin_Call struct {
	*mock.Call
}

// BUCPLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - inBody wire.SNAC_0x17_0x02_BUCPLoginRequest
//   - endpointCfg config.Endpoint
func (_e *mockAuthService_Expecter) BUCPLogin(ctx interface{}, inBody interface{}, endpointCfg interface{}) *mockAuthService_BUCPLogin_Call {
	return &mockAuthService_BUCPLogin_Call{Call: _e.mock.On("BUCPLogin", ctx, inBody, endpointCfg)}
}

func (_c *mockAuthService_BUCPLogin_Call) Run(run func(ctx context.Context, inBody wire.SNAC_0x17_0x02_BUCPLoginRequest, endpointCfg config.Endpoint)) *mockAuthService_BUCPLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.SNAC_0x17_0x02_BUCPLoginRequest
		if args[1] != nil {
			arg1 = args[1].(wire.SNAC_0x17_0x02_BUCPLoginRequest)
		}
		var arg2 config.Endpoint
		if args[2] != nil {
			arg2 = args[2].(config.Endpoint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthService_BUCPLogin_Call) Return(sNACMessage wire.SNACMessage, err error) *mockAuthService_BUCPLogin_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockAuthService_BUCPLogin_Call) RunAndReturn(run func(ctx context.Context, inBody wire.SNAC_0x17_0x02_BUCPLoginRequest, endpointCfg config.Endpoint) (wire.SNACMessage, error)) *mockAuthService_BUCPLogin_Call {
	_c.Call.Return(run)
	return _c
}

// CrackCookie provides a mock function for the type mockAuthService
func (_mock *mockAuthService) CrackCookie(authCookie []byte) (state.ServerCookie, error) {
	ret := _mock.Called(authCookie)

	if len(ret) == 0 {
		panic("no return value specified for CrackCookie")
	}

	var r0 state.ServerCookie
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (state.ServerCookie, error)); ok {
		return returnFunc(authCookie)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) state.ServerCookie); ok {
		r0 = returnFunc(authCookie)
	} else {
		r0 = ret.Get(0).(state.ServerCookie)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(authCookie)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_CrackCookie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CrackCookie'
type mockAuthService_CrackCookie_Call struct {
	*mock.Call
}

// CrackCookie is a helper method to define mock.On call
//   - authCookie []byte
func (_e *mockAuthService_Expecter) CrackCookie(authCookie interface{}) *mockAuthService_CrackCookie_Call {
	return &mockAuthService_CrackCookie_Call{Call: _e.mock.On("CrackCookie", authCookie)}
}

func (_c *mockAuthService_CrackCookie_Call) Run(run func(authCookie []byte)) *mockAuthService_CrackCookie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockAuthService_CrackCookie_Call) Return(serverCookie state.ServerCookie, err error) *mockAuthService_CrackCookie_Call {
	_c.Call.Return(serverCookie, err)
	return _c
}

func (_c *mockAuthService_CrackCookie_Call) RunAndReturn(run func(authCookie []byte) (state.ServerCookie, error)) *mockAuthService_CrackCookie_Call {
	_c.Call.Return(run)
	return _c
}

// FLAPLogin provides a mock function for the type mockAuthService
func (_mock *mockAuthService) FLAPLogin(ctx context.Context, inFrame wire.FLAPSignonFrame, endpointCfg config.Endpoint) (wire.TLVRestBlock, error) {
	ret := _mock.Called(ctx, inFrame, endpointCfg)

	if len(ret) == 0 {
		panic("no return value specified for FLAPLogin")
	}

	var r0 wire.TLVRestBlock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.FLAPSignonFrame, config.Endpoint) (wire.TLVRestBlock, error)); ok {
		return returnFunc(ctx, inFrame, endpointCfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wire.FLAPSignonFrame, config.Endpoint) wire.TLVRestBlock); ok {
		r0 = returnFunc(ctx, inFrame, endpointCfg)
	} else {
		r0 = ret.Get(0).(wire.TLVRestBlock)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wire.FLAPSignonFrame, config.Endpoint) error); ok {
		r1 = returnFunc(ctx, inFrame, endpointCfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_FLAPLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FLAPLogin'
type mockAuthService_FLAPLogin_Call struct {
	*mock.Call
}

// FLAPLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - inFrame wire.FLAPSignonFrame
//   - endpointCfg config.Endpoint
func (_e *mockAuthService_Expecter) FLAPLogin(ctx interface{}, inFrame interface{}, endpointCfg interface{}) *mockAuthService_FLAPLogin_Call {
	return &mockAuthService_FLAPLogin_Call{Call: _e.mock.On("FLAPLogin", ctx, inFrame, endpointCfg)}
}

func (_c *mockAuthService_FLAPLogin_Call) Run(run func(ctx context.Context, inFrame wire.FLAPSignonFrame, endpointCfg config.Endpoint)) *mockAuthService_FLAPLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wire.FLAPSignonFrame
		if args[1] != nil {
			arg1 = args[1].(wire.FLAPSignonFrame)
		}
		var arg2 config.Endpoint
		if args[2] != nil {
			arg2 = args[2].(config.Endpoint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthService_FLAPLogin_Call) Return(tLVRestBlock wire.TLVRestBlock, err error) *mockAuthService_FLAPLogin_Call {
	_c.Call.Return(tLVRestBlock, err)
	return _c
}

func (_c *mockAuthService_FLAPLogin_Call) RunAndReturn(run func(ctx context.Context, inFrame wire.FLAPSignonFrame, endpointCfg config.Endpoint) (wire.TLVRestBlock, error)) *mockAuthService_FLAPLogin_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterBOSSession provides a mock function for the type mockAuthService
func (_mock *mockAuthService) RegisterBOSSession(ctx context.Context, authCookie state.ServerCookie, cfg func(*state.Session)) (*state.SessionInstance, error) {
	ret := _mock.Called(ctx, authCookie, cfg)

	if len(ret) == 0 {
		panic("no return value specified for RegisterBOSSession")
	}

	var r0 *state.SessionInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.ServerCookie, func(*state.Session)) (*state.SessionInstance, error)); ok {
		return returnFunc(ctx, authCookie, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.ServerCookie, func(*state.Session)) *state.SessionInstance); ok {
		r0 = returnFunc(ctx, authCookie, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.SessionInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.ServerCookie, func(*state.Session)) error); ok {
		r1 = returnFunc(ctx, authCookie, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_RegisterBOSSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterBOSSession'
type mockAuthService_RegisterBOSSession_Call struct {
	*mock.Call
}

// RegisterBOSSession is a helper method to define mock.On call
//   - ctx context.Context
//   - authCookie state.ServerCookie
//   - cfg func(*state.Session)
func (_e *mockAuthService_Expecter) RegisterBOSSession(ctx interface{}, authCookie interface{}, cfg interface{}) *mockAuthService_RegisterBOSSession_Call {
	return &mockAuthService_RegisterBOSSession_Call{Call: _e.mock.On("RegisterBOSSession", ctx, authCookie, cfg)}
}

func (_c *mockAuthService_RegisterBOSSession_Call) Run(run func(ctx context.Context, authCookie state.ServerCookie, cfg func(*state.Session))) *mockAuthService_RegisterBOSSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.ServerCookie
		if args[1] != nil {
			arg1 = args[1].(state.ServerCookie)
		}
		var arg2 func(*state.Session)
		if args[2] != nil {
			arg2 = args[2].(func(*state.Session))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthService_RegisterBOSSession_Call) Return(sessionInstance *state.SessionInstance, err error) *mockAuthService_RegisterBOSSession_Call {
	_c.Call.Return(sessionInstance, err)
	return _c
}

func (_c *mockAuthService_RegisterBOSSession_Call) RunAndReturn(run func(ctx context.Context, authCookie state.ServerCookie, cfg func(*state.Session)) (*state.SessionInstance, error)) *mockAuthService_RegisterBOSSession_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterChatSession provides a mock function for the type mockAuthService
func (_mock *mockAuthService) RegisterChatSession(ctx context.Context, authCookie state.ServerCookie, cfg func(sess *state.Session)) (*state.SessionInstance, error) {
	ret := _mock.Called(ctx, authCookie, cfg)

	if len(ret) == 0 {
		panic("no return value specified for RegisterChatSession")
	}

	var r0 *state.SessionInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.ServerCookie, func(sess *state.Session)) (*state.SessionInstance, error)); ok {
		return returnFunc(ctx, authCookie, cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.ServerCookie, func(sess *state.Session)) *state.SessionInstance); ok {
		r0 = returnFunc(ctx, authCookie, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.SessionInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.ServerCookie, func(sess *state.Session)) error); ok {
		r1 = returnFunc(ctx, authCookie, cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_RegisterChatSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterChatSession'
type mockAuthService_RegisterChatSession_Call struct {
	*mock.Call
}

// RegisterChatSession is a helper method to define mock.On call
//   - ctx context.Context
//   - authCookie state.ServerCookie
//   - cfg func(sess *state.Session)
func (_e *mockAuthService_Expecter) RegisterChatSession(ctx interface{}, authCookie interface{}, cfg interface{}) *mockAuthService_RegisterChatSession_Call {
	return &mockAuthService_RegisterChatSession_Call{Call: _e.mock.On("RegisterChatSession", ctx, authCookie, cfg)}
}

func (_c *mockAuthService_RegisterChatSession_Call) Run(run func(ctx context.Context, authCookie state.ServerCookie, cfg func(sess *state.Session))) *mockAuthService_RegisterChatSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.ServerCookie
		if args[1] != nil {
			arg1 = args[1].(state.ServerCookie)
		}
		var arg2 func(sess *state.Session)
		if args[2] != nil {
			arg2 = args[2].(func(sess *state.Session))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAuthService_RegisterChatSession_Call) Return(sessionInstance *state.SessionInstance, err error) *mockAuthService_RegisterChatSession_Call {
	_c.Call.Return(sessionInstance, err)
	return _c
}

func (_c *mockAuthService_RegisterChatSession_Call) RunAndReturn(run func(ctx context.Context, authCookie state.ServerCookie, cfg func(sess *state.Session)) (*state.SessionInstance, error)) *mockAuthService_RegisterChatSession_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveBOSSession provides a mock function for the type mockAuthService
func (_mock *mockAuthService) RetrieveBOSSession(ctx context.Context, authCookie state.ServerCookie) (*state.SessionInstance, error) {
	ret := _mock.Called(ctx, authCookie)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveBOSSession")
	}

	var r0 *state.SessionInstance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.ServerCookie) (*state.SessionInstance, error)); ok {
		return returnFunc(ctx, authCookie)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, state.ServerCookie) *state.SessionInstance); ok {
		r0 = returnFunc(ctx, authCookie)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*state.SessionInstance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, state.ServerCookie) error); ok {
		r1 = returnFunc(ctx, authCookie)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAuthService_RetrieveBOSSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveBOSSession'
type mockAuthService_RetrieveBOSSession_Call struct {
	*mock.Call
}

// RetrieveBOSSession is a helper method to define mock.On call
//   - ctx context.Context
//   - authCookie state.ServerCookie
func (_e *mockAuthService_Expecter) RetrieveBOSSession(ctx interface{}, authCookie interface{}) *mockAuthService_RetrieveBOSSession_Call {
	return &mockAuthService_RetrieveBOSSession_Call{Call: _e.mock.On("RetrieveBOSSession", ctx, authCookie)}
}

func (_c *mockAuthService_RetrieveBOSSession_Call) Run(run func(ctx context.Context, authCookie state.ServerCookie)) *mockAuthService_RetrieveBOSSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 state.ServerCookie
		if args[1] != nil {
			arg1 = args[1].(state.ServerCookie)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAuthService_RetrieveBOSSession_Call) Return(sessionInstance *state.SessionInstance, err error) *mockAuthService_RetrieveBOSSession_Call {
	_c.Call.Return(sessionInstance, err)
	return _c
}

func (_c *mockAuthService_RetrieveBOSSession_Call) RunAndReturn(run func(ctx context.Context, authCookie state.ServerCookie) (*state.SessionInstance, error)) *mockAuthService_RetrieveBOSSession_Call {
	_c.Call.Return(run)
	return _c
}

// Signout provides a mock function for the type mockAuthService
func (_mock *mockAuthService) Signout(ctx context.Context, session *state.Session) {
	_mock.Called(ctx, session)
	return
}

// mockAuthService_Signout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signout'
type mockAuthService_Signout_Call struct {
	*mock.Call
}

// Signout is a helper method to define mock.On call
//   - ctx context.Context
//   - session *state.Session
func (_e *mockAuthService_Expecter) Signout(ctx interface{}, session interface{}) *mockAuthService_Signout_Call {
	return &mockAuthService_Signout_Call{Call: _e.mock.On("Signout", ctx, session)}
}

func (_c *mockAuthService_Signout_Call) Run(run func(ctx context.Context, session *state.Session)) *mockAuthService_Signout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAuthService_Signout_Call) Return() *mockAuthService_Signout_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockAuthService_Signout_Call) RunAndReturn(run func(ctx context.Context, session *state.Session)) *mockAuthService_Signout_Call {
	_c.Run(run)
	return _c
}

// SignoutChat provides a mock function for the type mockAuthService
func (_mock *mockAuthService) SignoutChat(ctx context.Context, sess *state.Session) {
	_mock.Called(ctx, sess)
	return
}

// mockAuthService_SignoutChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignoutChat'
type mockAuthService_SignoutChat_Call struct {
	*mock.Call
}

// SignoutChat is a helper method to define mock.On call
//   - ctx context.Context
//   - sess *state.Session
func (_e *mockAuthService_Expecter) SignoutChat(ctx interface{}, sess interface{}) *mockAuthService_SignoutChat_Call {
	return &mockAuthService_SignoutChat_Call{Call: _e.mock.On("SignoutChat", ctx, sess)}
}

func (_c *mockAuthService_SignoutChat_Call) Run(run func(ctx context.Context, sess *state.Session)) *mockAuthService_SignoutChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAuthService_SignoutChat_Call) Return() *mockAuthService_SignoutChat_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockAuthService_SignoutChat_Call) RunAndReturn(run func(ctx context.Context, sess *state.Session)) *mockAuthService_SignoutChat_Call {
	_c.Run(run)
	return _c
}
