// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toc

import (
	"context"

	"github.com/mk6i/open-oscar-server/config"
	"github.com/mk6i/open-oscar-server/state"
	"github.com/mk6i/open-oscar-server/wire"
	mock "github.com/stretchr/testify/mock"
)

// newMockOServiceService creates a new instance of mockOServiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOServiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOServiceService {
	mock := &mockOServiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockOServiceService is an autogenerated mock type for the OServiceService type
type mockOServiceService struct {
	mock.Mock
}

type mockOServiceService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOServiceService) EXPECT() *mockOServiceService_Expecter {
	return &mockOServiceService_Expecter{mock: &_m.Mock}
}

// ClientOnline provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) ClientOnline(ctx context.Context, service uint16, inBody wire.SNAC_0x01_0x02_OServiceClientOnline, instance *state.SessionInstance) error {
	ret := _mock.Called(ctx, service, inBody, instance)

	if len(ret) == 0 {
		panic("no return value specified for ClientOnline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, wire.SNAC_0x01_0x02_OServiceClientOnline, *state.SessionInstance) error); ok {
		r0 = returnFunc(ctx, service, inBody, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOServiceService_ClientOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientOnline'
type mockOServiceService_ClientOnline_Call struct {
	*mock.Call
}

// ClientOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - service uint16
//   - inBody wire.SNAC_0x01_0x02_OServiceClientOnline
//   - instance *state.SessionInstance
func (_e *mockOServiceService_Expecter) ClientOnline(ctx interface{}, service interface{}, inBody interface{}, instance interface{}) *mockOServiceService_ClientOnline_Call {
	return &mockOServiceService_ClientOnline_Call{Call: _e.mock.On("ClientOnline", ctx, service, inBody, instance)}
}

func (_c *mockOServiceService_ClientOnline_Call) Run(run func(ctx context.Context, service uint16, inBody wire.SNAC_0x01_0x02_OServiceClientOnline, instance *state.SessionInstance)) *mockOServiceService_ClientOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 wire.SNAC_0x01_0x02_OServiceClientOnline
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x01_0x02_OServiceClientOnline)
		}
		var arg3 *state.SessionInstance
		if args[3] != nil {
			arg3 = args[3].(*state.SessionInstance)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockOServiceService_ClientOnline_Call) Return(err error) *mockOServiceService_ClientOnline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOServiceService_ClientOnline_Call) RunAndReturn(run func(ctx context.Context, service uint16, inBody wire.SNAC_0x01_0x02_OServiceClientOnline, instance *state.SessionInstance) error) *mockOServiceService_ClientOnline_Call {
	_c.Call.Return(run)
	return _c
}

// IdleNotification provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) IdleNotification(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x01_0x11_OServiceIdleNotification) error {
	ret := _mock.Called(ctx, instance, inBody)

	if len(ret) == 0 {
		panic("no return value specified for IdleNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *state.SessionInstance, wire.SNAC_0x01_0x11_OServiceIdleNotification) error); ok {
		r0 = returnFunc(ctx, instance, inBody)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockOServiceService_IdleNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdleNotification'
type mockOServiceService_IdleNotification_Call struct {
	*mock.Call
}

// IdleNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - instance *state.SessionInstance
//   - inBody wire.SNAC_0x01_0x11_OServiceIdleNotification
func (_e *mockOServiceService_Expecter) IdleNotification(ctx interface{}, instance interface{}, inBody interface{}) *mockOServiceService_IdleNotification_Call {
	return &mockOServiceService_IdleNotification_Call{Call: _e.mock.On("IdleNotification", ctx, instance, inBody)}
}

func (_c *mockOServiceService_IdleNotification_Call) Run(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x01_0x11_OServiceIdleNotification)) *mockOServiceService_IdleNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.SessionInstance
		if args[1] != nil {
			arg1 = args[1].(*state.SessionInstance)
		}
		var arg2 wire.SNAC_0x01_0x11_OServiceIdleNotification
		if args[2] != nil {
			arg2 = args[2].(wire.SNAC_0x01_0x11_OServiceIdleNotification)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockOServiceService_IdleNotification_Call) Return(err error) *mockOServiceService_IdleNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockOServiceService_IdleNotification_Call) RunAndReturn(run func(ctx context.Context, instance *state.SessionInstance, inBody wire.SNAC_0x01_0x11_OServiceIdleNotification) error) *mockOServiceService_IdleNotification_Call {
	_c.Call.Return(run)
	return _c
}

// MonitorRateLimits provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) MonitorRateLimits(ctx context.Context, session *state.Session) {
	_mock.Called(ctx, session)
	return
}

// mockOServiceService_MonitorRateLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonitorRateLimits'
type mockOServiceService_MonitorRateLimits_Call struct {
	*mock.Call
}

// MonitorRateLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - session *state.Session
func (_e *mockOServiceService_Expecter) MonitorRateLimits(ctx interface{}, session interface{}) *mockOServiceService_MonitorRateLimits_Call {
	return &mockOServiceService_MonitorRateLimits_Call{Call: _e.mock.On("MonitorRateLimits", ctx, session)}
}

func (_c *mockOServiceService_MonitorRateLimits_Call) Run(run func(ctx context.Context, session *state.Session)) *mockOServiceService_MonitorRateLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *state.Session
		if args[1] != nil {
			arg1 = args[1].(*state.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockOServiceService_MonitorRateLimits_Call) Return() *mockOServiceService_MonitorRateLimits_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockOServiceService_MonitorRateLimits_Call) RunAndReturn(run func(ctx context.Context, session *state.Session)) *mockOServiceService_MonitorRateLimits_Call {
	_c.Run(run)
	return _c
}

// ServiceRequest provides a mock function for the type mockOServiceService
func (_mock *mockOServiceService) ServiceRequest(ctx context.Context, service uint16, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x01_0x04_OServiceServiceRequest, listenerGroup config.ListenerGroup) (wire.SNACMessage, error) {
	ret := _mock.Called(ctx, service, instance, inFrame, inBody, listenerGroup)

	if len(ret) == 0 {
		panic("no return value specified for ServiceRequest")
	}

	var r0 wire.SNACMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x01_0x04_OServiceServiceRequest, config.ListenerGroup) (wire.SNACMessage, error)); ok {
		return returnFunc(ctx, service, instance, inFrame, inBody, listenerGroup)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint16, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x01_0x04_OServiceServiceRequest, config.ListenerGroup) wire.SNACMessage); ok {
		r0 = returnFunc(ctx, service, instance, inFrame, inBody, listenerGroup)
	} else {
		r0 = ret.Get(0).(wire.SNACMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint16, *state.SessionInstance, wire.SNACFrame, wire.SNAC_0x01_0x04_OServiceServiceRequest, config.ListenerGroup) error); ok {
		r1 = returnFunc(ctx, service, instance, inFrame, inBody, listenerGroup)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockOServiceService_ServiceRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceRequest'
type mockOServiceService_ServiceRequest_Call struct {
	*mock.Call
}

// ServiceRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - service uint16
//   - instance *state.SessionInstance
//   - inFrame wire.SNACFrame
//   - inBody wire.SNAC_0x01_0x04_OServiceServiceRequest
//   - listenerGroup config.ListenerGroup
func (_e *mockOServiceService_Expecter) ServiceRequest(ctx interface{}, service interface{}, instance interface{}, inFrame interface{}, inBody interface{}, listenerGroup interface{}) *mockOServiceService_ServiceRequest_Call {
	return &mockOServiceService_ServiceRequest_Call{Call: _e.mock.On("ServiceRequest", ctx, service, instance, inFrame, inBody, listenerGroup)}
}

func (_c *mockOServiceService_ServiceRequest_Call) Run(run func(ctx context.Context, service uint16, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x01_0x04_OServiceServiceRequest, listenerGroup config.ListenerGroup)) *mockOServiceService_ServiceRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint16
		if args[1] != nil {
			arg1 = args[1].(uint16)
		}
		var arg2 *state.SessionInstance
		if args[2] != nil {
			arg2 = args[2].(*state.SessionInstance)
		}
		var arg3 wire.SNACFrame
		if args[3] != nil {
			arg3 = args[3].(wire.SNACFrame)
		}
		var arg4 wire.SNAC_0x01_0x04_OServiceServiceRequest
		if args[4] != nil {
			arg4 = args[4].(wire.SNAC_0x01_0x04_OServiceServiceRequest)
		}
		var arg5 config.ListenerGroup
		if args[5] != nil {
			arg5 = args[5].(config.ListenerGroup)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockOServiceService_ServiceRequest_Call) Return(sNACMessage wire.SNACMessage, err error) *mockOServiceService_ServiceRequest_Call {
	_c.Call.Return(sNACMessage, err)
	return _c
}

func (_c *mockOServiceService_ServiceRequest_Call) RunAndReturn(run func(ctx context.Context, service uint16, instance *state.SessionInstance, inFrame wire.SNACFrame, inBody wire.SNAC_0x01_0x04_OServiceServiceRequest, listenerGroup config.ListenerGroup) (wire.SNACMessage, error)) *mockOServiceService_ServiceRequest_Call {
	_c.Call.Return(run)
	return _c
}
